### ISSUE TITLE
Collect Fingerprint Pro data from website in Redshift

### ISSUE THREAD

**Issue by bwegrzyn** [fingerprintjs/fingerprint.com#762]
We want to start collecting data about all the visitor's activity we get from our solution. We want to send this data to our Redshift warehouse to use it for better marketing attribution. We want to gather info about pages visited, timestamp of visit occurrence and data we have in our API response.

Original ticket: https://fpjs.myjetbrains.com/youtrack/issue/DASH-1272/Collecting-Fingerprint-Pro-data-from-our-website-in-Redshift

**Comment by Zaciesh** [comment]
As a Product Analyst, I would like to upvote this request. Having data in Sigma allows using custom SQL on data for more specific insights which is not supported in the Amplitude package we have.

**Comment by bwegrzyn** [comment]
@Zaciesh Could you provide some more details on how you envision this working?

With regards to custom SQL not being available on our Amplitude package, is this something that could be solved by upgrading the package? Or would we still want this data in Redshift?

**Comment by macprofpjs** [comment]
We want to store this fields from each request in elvo subscription installed on our website in either MGMT-DB or Redshift.

-visitorId
-   timestamp
-   time
-   incognito
-   url
-   clientReferrer
-   ipLocation.city
-   ipLocation.country.code
-   ipLocation.country.name
-   ipLocation.timezone
-   ipLocation.subdivisions.isocode
-   browserDetails.browserName
-   browserDetails.os
-   browserDetails.device
-   confidence
-   firstSeenAt.global
-   firstSeenAt.subscription
-   lastSeenAt.global
-   lastSeenAt.subscription

**Comment by Zaciesh** [comment]
@bwegrzyn, it would be ideal if it could work as any other connection in Sigma. 

My use case would be as follows: whenever I would like to derive insights from the Fingerprint data captured for our Elvo site, I would log in to Sigma, get into the respective data connection and query table of events. The sample of the data available has been shared with me as the following file: [elvo_since1673308800000_before1674678293730.csv](https://github.com/fingerprintjs/fingerprint.com/files/10538920/elvo_since1673308800000_before1674678293730.csv). The current work that would be useful is marketing attribution insights based on all the Elvo data captured. 

> With regards to custom SQL not being available on our Amplitude package, is this something that could be solved by upgrading the package?

The data we want to access is also historical and haven't been captured by Amplitude as it wasn't instrumented to do so. It's not possible to load historical events either to use any of the existing Amplitude's functionality. Therefore, Sigma is the only solution here and also the most suitable not only because of the SQL, but all the BI tools it includes. Moving forward, we could instrument amplitude to capture more relevant data, but it will take time to do so, and also to capture data to derive any insights.

On the note of any Amplitude's upgrades - it seems to me that it works as Jira, where you have a core products and a ton of add-ons / plugins. There have been other add-ons that seem to have a higher urgency from analytics point of view, but I'm still reviewing what we have before requesting anything new. 

Please let me know if you have any other questions.

**Comment by dcorso21** [comment]
This would involve:
1. setting up a webhook to send event information from elvo.
2. creating a new endpoint like `/fp/webhook` in the mgmt api.
3. creating a new table to store these events
4. ensuring this data propagates to sigma (I remember some tables had to be specified in metabase, don't know if sigma works the same way).


Considerations: 
- Is there a preference we have for storing them in the mgmt-api db vs redshift? I don't have a preference but it may be easier to set up in the mgmt-api db since our team is more familiar.
- We should add IP-based access to the `/fp/webhook` endpoint. I believe we have the IPs on our docs, but should be able to find them internally.

Time estimation based on these steps: Maybe 3 days.

CC @bwegrzyn

**Comment by macprofpjs** [comment]
We have no preference for storing that in mgmt-api db vs redshift since moving it to Redshift will be a 5 minute setup for me.

**Comment by dcorso21** [comment]
Here is a zip containing the historical data from Nov 22nd until today just for reference:
[elvo_historical_data.zip](https://github.com/fingerprintjs/fingerprint.com/files/10807162/elvo_historical_data.zip)

**Comment by dcorso21** [comment]
Also, @macprofpjs just so you know we can retrieve this data via retool > customer search page > subscription > actions > export visit history. It is the same as getting it from the server API, so it stops being stored after ~3 months.

**Comment by dcorso21** [comment]
@macprofpjs @spalt08 The plan so far is to create an API gateway and Lambda in AWS, create a simple webhook handler and insert the data into the redshift instance directly. After it is created by #web-team, we can hand it off to revops. 

Please let me know if I can assist.

**Comment by dcorso21** [comment]
we're in the process of setting it up in retool.
